CREATE TABLE TB_TIPO_PRODUTO(ID_TIPO_PRODUTO INT(4)      NOT NULL AUTO_INCREMENT,
					         DS_TIPO_PRODUTO VARCHAR(50) NOT NULL,
							 PRIMARY KEY (ID_TIPO_PRODUTO));

CREATE TABLE TB_TIPO_PEDIDO(ID_TIPO_PEDIDO INT(4)      NOT NULL AUTO_INCREMENT,
					  		DS_TIPO_PEDIDO VARCHAR(50) NOT NULL,
							PRIMARY KEY (ID_TIPO_PEDIDO));

CREATE TABLE TB_TIPO_FILIAL(ID_TIPO_FILIAL INT(4)      NOT NULL AUTO_INCREMENT,
					        DS_TIPO_FILIAL VARCHAR(50) NOT NULL,
							PRIMARY KEY (ID_TIPO_FILIAL));

CREATE TABLE TB_TIPO_PAGAMENTO(ID_TIPO_PAGAMENTO INT(4)      NOT NULL AUTO_INCREMENT,
					           DS_TIPO_PAGAMENTO VARCHAR(50) NOT NULL,
							   PRIMARY KEY (ID_TIPO_PAGAMENTO));

CREATE TABLE TB_TIPO_MOVIMENTACOES(ID_TIPO_MOVIMENTACAO INT(4)      NOT NULL AUTO_INCREMENT,
					               DS_TIPO_MOVIMENTACAO   VARCHAR(50) NOT NULL,
								   PRIMARY KEY (ID_TIPO_MOVIMENTACAO));

CREATE TABLE TB_TIPO_OPERACAO(ID_TIPO_OPERACAO  INT(4)      NOT NULL AUTO_INCREMENT,
					          DS_TIPO_OPERACAO VARCHAR(50) NOT NULL,
							  PRIMARY KEY (ID_TIPO_OPERACAO));

CREATE TABLE TB_STATUS_NOTA(ID_STATUS_NOTA  INT(4)       NOT NULL AUTO_INCREMENT,
					        DS_STATUS_NOTA VARCHAR(50) NOT NULL,
							PRIMARY KEY (ID_STATUS_NOTA));

CREATE TABLE TB_FORNECEDOR(ID_FORNECEDOR   BIGINT(12)  NOT NULL AUTO_INCREMENT,
					       NM_RAZAO_SOCIAL VARCHAR(50) NOT NULL,
						   DS_CNPJ         VARCHAR(14) NOT NULL,
					       FL_FABRICANTE   INT(1)      NOT NULL DEFAULT 0,
						   DT_CADASTRO     DATE        NOT NULL DEFAULT date_format(date_format(current_date(), '%d/%m/%Y'), '%d/%m/%Y'),        
						   PRIMARY KEY (ID_FORNECEDOR));
			 
CREATE TABLE TB_CLIENTE(ID_CLIENTE  BIGINT(12)   NOT NULL AUTO_INCREMENT,
						NM_CLIENTE  VARCHAR(100) NOT NULL,
						DS_CPF      VARCHAR(11)  NOT NULL,
						DT_CADASTRO DATE         NOT NULL DEFAULT date_format(current_date(), '%d/%m/%Y'),
						PRIMARY KEY (ID_CLIENTE));
			 
CREATE TABLE TB_FILIAL(ID_FILIAL      BIGINT(6)   NOT NULL AUTO_INCREMENT,
					   ID_TIPO_FILIAL INT(4)      NOT NULL,
					   DS_CNPJ        VARCHAR(14) NOT NULL,
					   NM_FILIAL      VARCHAR(50) NOT NULL,
					   DT_CADASTRO    DATE        NOT NULL DEFAULT date_format(current_date(), '%d/%m/%Y'),
					   PRIMARY KEY (ID_FILIAL));			 
			 
CREATE TABLE TB_PRODUTO(ID_PRODUTO      BIGINT(8)   NOT NULL AUTO_INCREMENT,
						DS_PRODUTO      VARCHAR(50) NOT NULL,
						ID_TIPO_PRODUTO INT(4)      NOT NULL,
						FL_CONTROLADO   INT(1)      NOT NULL DEFAULT 0,
						DT_CADASTRO     DATE        NOT NULL DEFAULT date_format(current_date(), '%d/%m/%Y'),
						PRIMARY KEY (ID_PRODUTO));
			 
CREATE TABLE TB_PEDIDO(ID_PEDIDO       BIGINT(12)   NOT NULL AUTO_INCREMENT,
					   DT_PEDIDO       DATE         NOT NULL DEFAULT date_format(current_date(), '%d/%m/%Y'),
					   NR_PEDIDO       BIGINT(12)   NOT NULL,
					   ID_TIPO_PEDIDO  INT(4)       NOT NULL,
					   ID_CLIENTE      BIGINT(12)   NULL,
					   ID_FORNECEDOR   BIGINT(12)   NULL,
					   ID_FILIAL       BIGINT(6)    NOT NULL,
					   VL_TOTAL_PEDIDO DOUBLE(12,2) NOT NULL,
					   PRIMARY KEY (ID_PEDIDO));

CREATE TABLE TB_PEDIDO_ITEM(ID_PEDIDO      BIGINT(12)   NOT NULL,
							NR_PEDIDO_ITEM INT(4)       NOT NULL,
							ID_PRODUTO     BIGINT(8)    NOT NULL,
							QT_ITEM        INT(6)       NOT NULL,
							VL_UNITARIO    DOUBLE(12,2) NOT NULL,
							PRIMARY KEY (ID_PEDIDO, NR_PEDIDO_ITEM));
							
CREATE TABLE TB_NF(ID_NF             BIGINT(12)   NOT NULL AUTO_INCREMENT,
				   ID_TIPO_OPERACAO  INT(4)       NOT NULL,
				   ID_STATUS_NOTA    INT(4)       NOT NULL,
				   DT_EMISSAO        DATE         NOT NULL DEFAULT date_format(current_date(), '%d/%m/%Y'), 
				   NR_NOTA           BIGINT       NOT NULL,
				   ID_CLIENTE        BIGINT(12)   NULL,
				   ID_FORNECEDOR     BIGINT(12)   NULL,
				   ID_FILIAL         BIGINT(6)    NOT NULL,
				   ID_TIPO_PAGAMENTO INT(4)       NOT NULL,
				   VL_TOTAL_NOTA     DOUBLE(12,2) NOT NULL,
				   PRIMARY KEY (ID_NF));
					
CREATE TABLE TB_NF_ITEM(ID_NF       BIGINT(12)   NOT NULL,
						NR_NF_ITEM  INT(4)       NOT NULL,
						ID_PRODUTO  BIGINT(8)    NOT NULL,
						QT_ITEM     INT(6)       NOT NULL,
						VL_UNITARIO DOUBLE(12,2) NOT NULL,
						PRIMARY KEY (ID_NF, NR_NF_ITEM));

CREATE TABLE TB_MOVIMENTACOES(ID_MOVIMENTACAO      BIGINT(12) NOT NULL AUTO_INCREMENT,
							  ID_NF                BIGINT(12) NOT NULL,
							  ID_TIPO_MOVIMENTACAO INT(4)     NOT NULL,
							  FL_PROCESSADO        INT(1)     NOT NULL DEFAULT 0,
							  DT_MOVIMENTACAO      DATE       NOT NULL DEFAULT date_format(current_date(), '%d/%m/%Y'),
							  PRIMARY KEY (ID_MOVIMENTACAO));

CREATE TABLE TB_ESTOQUE(ID_FILIAL             BIGINT(6) NULL,
                        ID_PRODUTO            BIGINT(8) NULL,
						QT_ESTOQUE_DISPONIVEL BIGINT(8) NULL);		
						
ALTER TABLE TB_FILIAL        ADD CONSTRAINT FK_ID_TIPO_FILIAL        FOREIGN KEY (ID_TIPO_FILIAL)       REFERENCES TB_TIPO_FILIAL(ID_TIPO_FILIAL)         ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TB_PRODUTO       ADD CONSTRAINT FK_ID_TIPO_PRODUTO       FOREIGN KEY (ID_TIPO_PRODUTO)      REFERENCES TB_TIPO_PRODUTO(ID_TIPO_PRODUTO) 	  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TB_PEDIDO        ADD CONSTRAINT FK_ID_TIPO_PEDIDO        FOREIGN KEY (ID_TIPO_PEDIDO)       REFERENCES TB_TIPO_PEDIDO(ID_TIPO_PEDIDO) 		  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TB_PEDIDO        ADD CONSTRAINT FK_ID_CLIENTE            FOREIGN KEY (ID_CLIENTE)           REFERENCES TB_CLIENTE(ID_CLIENTE) 				  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TB_PEDIDO        ADD CONSTRAINT FK_ID_FORNECEDOR         FOREIGN KEY (ID_FORNECEDOR)        REFERENCES TB_FORNECEDOR(ID_FORNECEDOR) 		  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TB_PEDIDO        ADD CONSTRAINT FK_ID_FILIAL             FOREIGN KEY (ID_FILIAL)            REFERENCES TB_FILIAL(ID_FILIAL) 				  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TB_PEDIDO_ITEM   ADD CONSTRAINT FK_ID_PEDIDO_ITEM        FOREIGN KEY (ID_PEDIDO)            REFERENCES TB_PEDIDO(ID_PEDIDO) 				  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TB_PEDIDO_ITEM   ADD CONSTRAINT FK_ID_PRODUTO            FOREIGN KEY (ID_PRODUTO)           REFERENCES TB_PRODUTO(ID_PRODUTO) 				  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TB_NF            ADD CONSTRAINT FK_ID_TIPO_OPERACAO      FOREIGN KEY (ID_TIPO_OPERACAO)     REFERENCES TB_TIPO_OPERACAO(ID_TIPO_OPERACAO) 	  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TB_NF            ADD CONSTRAINT FK_ID_STATUS_NOTA        FOREIGN KEY (ID_STATUS_NOTA)       REFERENCES TB_STATUS_NOTA(ID_STATUS_NOTA) 	      ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TB_NF            ADD CONSTRAINT FK_ID_CLIENTE_NF         FOREIGN KEY (ID_CLIENTE)           REFERENCES TB_CLIENTE(ID_CLIENTE) 				  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TB_NF            ADD CONSTRAINT FK_ID_FORNECEDOR_NF      FOREIGN KEY (ID_FORNECEDOR)        REFERENCES TB_FORNECEDOR(ID_FORNECEDOR) 		  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TB_NF            ADD CONSTRAINT FK_ID_FILIAL_NF          FOREIGN KEY (ID_FILIAL)            REFERENCES TB_FILIAL(ID_FILIAL) 				  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TB_NF            ADD CONSTRAINT FK_ID_TIPO_PAGAMENTO     FOREIGN KEY (ID_TIPO_PAGAMENTO)    REFERENCES TB_TIPO_PAGAMENTO(ID_TIPO_PAGAMENTO)   ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TB_NF_ITEM       ADD CONSTRAINT FK_ID_NF_ITEM            FOREIGN KEY (ID_NF)                REFERENCES TB_NF(ID_NF) 						  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TB_NF_ITEM       ADD CONSTRAINT FK_ID_PRODUTO_NF         FOREIGN KEY (ID_PRODUTO)           REFERENCES TB_PRODUTO(ID_PRODUTO) 				  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TB_ESTOQUE       ADD CONSTRAINT FK_ID_FILIAL_ESTOQUE     FOREIGN KEY (ID_FILIAL)            REFERENCES TB_FILIAL(ID_FILIAL) 				  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TB_ESTOQUE       ADD CONSTRAINT FK_ID_PRODUTO_ESTOQUE    FOREIGN KEY (ID_PRODUTO)           REFERENCES TB_PRODUTO(ID_PRODUTO) 				  ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TB_MOVIMENTACOES ADD CONSTRAINT FK_ID_TIPO_MOVIMENTACAO  FOREIGN KEY (ID_TIPO_MOVIMENTACAO) REFERENCES TB_TIPO_MOVIMENTACOES(ID_TIPO_MOVIMENTACAO) ON DELETE NO ACTION ON UPDATE NO ACTION;
ALTER TABLE TB_MOVIMENTACOES  ADD CONSTRAINT FK_ID_NF_MOVIMENTACOES  FOREIGN KEY (ID_NF)                REFERENCES TB_NF(ID_NF) 						  ON DELETE NO ACTION ON UPDATE NO ACTION;


-- TIPOS                                                 
insert into tb_tipo_filial        (ds_tipo_filial)       values('CENTRO DE DISRIBUICAO');
insert into tb_tipo_filial        (ds_tipo_filial)       values('LOJA');
insert into tb_tipo_pedido        (ds_tipo_pedido)       values('COMPRA');
insert into tb_tipo_pedido        (ds_tipo_pedido)       values('VENDA');
insert into tb_tipo_produto       (ds_tipo_produto)      values('MEDICAMENTO');
insert into tb_tipo_produto       (ds_tipo_produto)      values('OTC');
insert into tb_tipo_produto       (ds_tipo_produto)      values('PERFUMARIA');
insert into tb_tipo_pagamento     (ds_tipo_pagamento)    values('BOLETO');
insert into tb_tipo_pagamento     (ds_tipo_pagamento)    values('CARTÃO DE CRÉDITO');
insert into tb_tipo_pagamento     (ds_tipo_pagamento)    values('DÉBITO EM CONTA');
insert into tb_tipo_operacao      (ds_tipo_operacao)     values('COMPRA FORNECEDORES');
insert into tb_tipo_operacao      (ds_tipo_operacao)     values('VENDA CLIENTE');
insert into tb_tipo_operacao      (ds_tipo_operacao)     values('TRANSFERENCIA CD ==> LOJA');
insert into tb_status_nota        (ds_status_nota)       values('PENDENTE');
insert into tb_status_nota        (ds_status_nota)       values('PROCESSADA');
insert into tb_status_nota        (ds_status_nota)       values('EFETIVADA NO ESTOQUE');
insert into tb_tipo_movimentacoes (ds_tipo_movimentacao) values('ENTRADA');
insert into tb_tipo_movimentacoes (ds_tipo_movimentacao) values('SAIDA');

-- PRODUTO
INSERT INTO TB_PRODUTO(DS_PRODUTO, ID_TIPO_PRODUTO, FL_CONTROLADO, DT_CADASTRO) VALUES('LEXOTAN',1,1,date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_PRODUTO(DS_PRODUTO, ID_TIPO_PRODUTO, FL_CONTROLADO, DT_CADASTRO) VALUES('CATAFLAM',1,0,date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_PRODUTO(DS_PRODUTO, ID_TIPO_PRODUTO, FL_CONTROLADO, DT_CADASTRO) VALUES('DORFLEX',2,0,date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_PRODUTO(DS_PRODUTO, ID_TIPO_PRODUTO, FL_CONTROLADO, DT_CADASTRO) VALUES('SHAMPOO CLEAR',3,0,date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_PRODUTO(DS_PRODUTO, ID_TIPO_PRODUTO, FL_CONTROLADO, DT_CADASTRO) VALUES('RIVOTRIL',1,1,date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_PRODUTO(DS_PRODUTO, ID_TIPO_PRODUTO, FL_CONTROLADO, DT_CADASTRO) VALUES('AMOXICILINA',1,1,date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_PRODUTO(DS_PRODUTO, ID_TIPO_PRODUTO, FL_CONTROLADO, DT_CADASTRO) VALUES('EPAREMA',2,0,date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_PRODUTO(DS_PRODUTO, ID_TIPO_PRODUTO, FL_CONTROLADO, DT_CADASTRO) VALUES('SABONETE LIQUIDO',3,0,date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_PRODUTO(DS_PRODUTO, ID_TIPO_PRODUTO, FL_CONTROLADO, DT_CADASTRO) VALUES('NASONEX',1,0,date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_PRODUTO(DS_PRODUTO, ID_TIPO_PRODUTO, FL_CONTROLADO, DT_CADASTRO) VALUES('NEOSALDINA',2,0,date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_PRODUTO(DS_PRODUTO, ID_TIPO_PRODUTO, FL_CONTROLADO, DT_CADASTRO) VALUES('DICOXIBE',1,1,date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_PRODUTO(DS_PRODUTO, ID_TIPO_PRODUTO, FL_CONTROLADO, DT_CADASTRO) VALUES('ALCOOL EM GEL',3,0,date_format(current_date(), '%d/%m/%Y'));


-- FORNECEDOR
INSERT INTO TB_FORNECEDOR(NM_RAZAO_SOCIAL, DS_CNPJ, FL_FABRICANTE, DT_CADASTRO) VALUES('ROCHE','06298356000110',1,date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_FORNECEDOR(NM_RAZAO_SOCIAL, DS_CNPJ, FL_FABRICANTE, DT_CADASTRO) VALUES('ACHE','55447912000151',1,date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_FORNECEDOR(NM_RAZAO_SOCIAL, DS_CNPJ, FL_FABRICANTE, DT_CADASTRO) VALUES('P & G','01786543000187',1,date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_FORNECEDOR(NM_RAZAO_SOCIAL, DS_CNPJ, FL_FABRICANTE, DT_CADASTRO) VALUES('SANTA CRUZ','89756792000110',0,date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_FORNECEDOR(NM_RAZAO_SOCIAL, DS_CNPJ, FL_FABRICANTE, DT_CADASTRO) VALUES('PANPHARMA','09643009000181',0,date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_FORNECEDOR(NM_RAZAO_SOCIAL, DS_CNPJ, FL_FABRICANTE, DT_CADASTRO) VALUES('NEO QUIMICA','21889098000120',1,date_format(current_date(), '%d/%m/%Y'));

-- FILIAL
INSERT INTO TB_FILIAL(ID_TIPO_FILIAL, DS_CNPJ, NM_FILIAL, DT_CADASTRO) VALUES(1,'22889098000187','CD EMBU',date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_FILIAL(ID_TIPO_FILIAL, DS_CNPJ, NM_FILIAL, DT_CADASTRO) VALUES(1,'01973567000112','CD CURITIBA',date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_FILIAL(ID_TIPO_FILIAL, DS_CNPJ, NM_FILIAL, DT_CADASTRO) VALUES(1,'19234765000188','CD SALVADOR',date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_FILIAL(ID_TIPO_FILIAL, DS_CNPJ, NM_FILIAL, DT_CADASTRO) VALUES(1,'91001896000144','CD DUQUE DE CAXIAS',date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_FILIAL(ID_TIPO_FILIAL, DS_CNPJ, NM_FILIAL, DT_CADASTRO) VALUES(2,'23650289000154','CONJUNTO NACIONAL',date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_FILIAL(ID_TIPO_FILIAL, DS_CNPJ, NM_FILIAL, DT_CADASTRO) VALUES(2,'11207361000195','ALTO DA XV',date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_FILIAL(ID_TIPO_FILIAL, DS_CNPJ, NM_FILIAL, DT_CADASTRO) VALUES(2,'30701793000169','COPACABANA - B',date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_FILIAL(ID_TIPO_FILIAL, DS_CNPJ, NM_FILIAL, DT_CADASTRO) VALUES(2,'17999333000177','FAROL DA BARRA',date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_FILIAL(ID_TIPO_FILIAL, DS_CNPJ, NM_FILIAL, DT_CADASTRO) VALUES(2,'44792832000110','ALPHAVILLE - A',date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_FILIAL(ID_TIPO_FILIAL, DS_CNPJ, NM_FILIAL, DT_CADASTRO) VALUES(2,'66701832000189','SHOPPING TAMBORE',date_format(current_date(), '%d/%m/%Y'));

-- CLIENTE
INSERT INTO TB_CLIENTE(NM_CLIENTE, DS_CPF, DT_CADASTRO) VALUES('HUGUINHO','81926701378',date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_CLIENTE(NM_CLIENTE, DS_CPF, DT_CADASTRO) VALUES('ZEZINHO','02856256251',date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_CLIENTE(NM_CLIENTE, DS_CPF, DT_CADASTRO) VALUES('LUIZINHO','99987267265',date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_CLIENTE(NM_CLIENTE, DS_CPF, DT_CADASTRO) VALUES('CAPITAO BOEING','93691740111',date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_CLIENTE(NM_CLIENTE, DS_CPF, DT_CADASTRO) VALUES('PATO DONALD','56423198766',date_format(current_date(), '%d/%m/%Y'));
INSERT INTO TB_CLIENTE(NM_CLIENTE, DS_CPF, DT_CADASTRO) VALUES('GASTAO','32183892644',date_format(current_date(), '%d/%m/%Y'));

-- ESTOQUE
insert into tb_estoque(id_filial, id_produto, qt_estoque_disponivel) select 1,p.id_produto,0 from tb_produto p;
insert into tb_estoque(id_filial, id_produto, qt_estoque_disponivel) select 2,p.id_produto,0 from tb_produto p;
insert into tb_estoque(id_filial, id_produto, qt_estoque_disponivel) select 3,p.id_produto,0 from tb_produto p;
insert into tb_estoque(id_filial, id_produto, qt_estoque_disponivel) select 4,p.id_produto,0 from tb_produto p;
insert into tb_estoque(id_filial, id_produto, qt_estoque_disponivel) select 5,p.id_produto,0 from tb_produto p;
insert into tb_estoque(id_filial, id_produto, qt_estoque_disponivel) select 6,p.id_produto,0 from tb_produto p;
insert into tb_estoque(id_filial, id_produto, qt_estoque_disponivel) select 7,p.id_produto,0 from tb_produto p;
insert into tb_estoque(id_filial, id_produto, qt_estoque_disponivel) select 8,p.id_produto,0 from tb_produto p;
insert into tb_estoque(id_filial, id_produto, qt_estoque_disponivel) select 9,p.id_produto,0 from tb_produto p;
insert into tb_estoque(id_filial, id_produto, qt_estoque_disponivel) select 10,p.id_produto,0 from tb_produto p;	 
